#SPDX-License-Identifier: MIT-0
---
# tasks file for test-role
- name: first install apache2
  action: apt name='{{pkgname}}' state=present
  notify: service installed #notify name and handler name must same
